version: "3.8"
services:
  # caddy:
  #   image: caddy:2-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   restart: unless-stopped
  #   environment:
  #     - ACME_AGREE=true
    # labels:
    #   caddy: example.com
    #   caddy.reverse_proxy: "{{upstreams 3000}}"

  server:
    restart: always
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env

# volumes:
#   caddy_data:
#   caddy_config:
